language: java
on: [push]

jobs:
 check-bats-version:
  runs-on: ubuntu-latest
  steps:
   - run: mvn test-compile -pl . -am
   - run: mvn -pl . test -Dtest=org.springframework.data.couchbase.core.mapping.MappingCouchbaseConverterTests#idHasAnnotatedIdAndMultipleIdFieldsReverse
